// SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using DataModel;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Text.RegularExpressions;

namespace Helper.Converters
{   
    public class EventEventShortConverter
    {
        //Convert Event to EventV2
        private static EventShortLinked ConvertEventToEventShort(
            EventLinked eventv1
        )
        {
            EventShortLinked eventshort = new EventShortLinked();

            eventshort.PublishedOn = eventv1.PublishedOn;
            eventshort.Id = eventv1.Id;
            eventshort.ImageGallery = eventv1.ImageGallery;
            eventshort.TagIds = eventv1.TagIds;
            eventshort.Tags = eventv1.Tags;
            eventshort.Active = eventv1.Active;

            eventshort.Detail = eventv1.Detail;
            eventshort.Source = eventv1.Source;

            eventshort.GpsInfo = eventv1.GpsInfo;
            eventshort.Mapping = eventv1.Mapping;

            eventshort.StartDate = eventv1.DateBegin == null ? (DateTime)eventv1.DateBegin : DateTime.MinValue;
            eventshort.EndDate = eventv1.DateEnd == null ? (DateTime)eventv1.DateEnd : DateTime.MinValue;

            eventshort.FirstImport = eventv1.FirstImport;
            eventshort.LastChange = eventv1.LastChange;
            eventshort.Shortname = eventv1.Shortname;

            eventshort.HasLanguage = eventv1.HasLanguage;

            eventshort.LicenseInfo = eventv1.LicenseInfo;

            eventshort.RelatedContent = eventv1.RelatedContent;

            //eventshort.ChangedOn = eventv1.LastChange;

            //TODO Convert
            //eventshort.StartDateUTC = 
            //eventshort.EndDateUTC =


            //Fields to map
            //EventId
            //SoldOut
            //Display1 - Display9            
            //ActiveWeb
            //ActiveToday
            //CompanyId
            //Documents
            //EventText   --> in Detail.Basetext
            //EventDescription
            //EventDescriptionDE
            //EventDescriptionEN
            //EventDescriptionIT
            //EventTextDE
            //EventTextEN
            //EventTextIT
            //EventTitle  --> in Detail.Title
            //GpsPoints   --> Autogenerated
            //CustomTagging --> Migrated to Tags
            //TypicalAgeRange


            //VideoUrl
            //VideoItems
            //WebAddress
            //AnchorVenue
            //AnchorVenueShort
            //AnchorVenueRoomMapping
            //EventDocument
            //EventLocation
            //AdditionalProperties


            //ContactFax
            //ContactCity
            //ContactEmail
            //ContactAddressLine1
            //ContactPhone
            //ContactCountry
            //ContactLastName
            //ContactFirstName

            //ContactCell
            //ContactCode
            //ContactAddressLine2
            //ContactAddressLine3

            var contactinfo = eventv1.ContactInfos.FirstOrDefault().Value;
            eventshort.ContactFax = contactinfo.Faxnumber;
            eventshort.ContactCity = contactinfo.City;
            eventshort.ContactAddressLine1 = contactinfo.ZipCode + " " + contactinfo.Address;
            eventshort.ContactEmail = contactinfo.Email;
            eventshort.ContactCountry = contactinfo.CountryName;
            eventshort.ContactPhone = contactinfo.Phonenumber;
            eventshort.ContactLastName = contactinfo.Surname;
            eventshort.ContactFirstName = contactinfo.Givenname;
            eventshort.ContactAddressLine2 = contactinfo.Area;
            eventshort.ContactAddressLine3 = contactinfo.Region;
            
            //CompanyFax
            //CompanyUrl
            //CompanyCity
            //CompanyMail
            //CompanyName
            //CompanyPhone
            //CompanyCountry
            //CompanyAddressLine1
            //CompanyAddressLine2
            //CompanyAddressLine3
            var organizerinfo = eventv1.OrganizerInfos.FirstOrDefault().Value;
            eventshort.CompanyFax = organizerinfo.Faxnumber;
            eventshort.CompanyCity = organizerinfo.City;
            eventshort.CompanyAddressLine1 = organizerinfo.ZipCode + " " + organizerinfo.Address;
            eventshort.CompanyMail = organizerinfo.Email;
            eventshort.CompanyCountry = organizerinfo.CountryName;
            eventshort.CompanyPhone = organizerinfo.Phonenumber;
            eventshort.CompanyName = organizerinfo.CompanyName;            
            eventshort.CompanyAddressLine2 = organizerinfo.Area;
            eventshort.CompanyAddressLine3 = organizerinfo.Region;
            eventshort.CompanyUrl = organizerinfo.Url;


            eventshort.WebAddress = contactinfo.Url;


            foreach (var eventdate in eventv1.EventDate)
            {
                RoomBooked myroom = new RoomBooked();
                //Space
                //Comment
                //StartDate
                //StartDateUTC
                //EndDate
                //EndDateUTC
                //Subtitle
                //SpaceDesc
                //SpaceType
                //SpaceAbbrev
                ////ContactFax
            }
            
            return eventshort;
        }

        //Convert EventShort to EventV2
        private static EventLinked ConvertEventShortToEvent(
            EventShortLinked eventvshort
        )
        {
            EventLinked eventv1 = new EventLinked();

            eventv1.Id = eventvshort.Id;

            return eventv1;
        }
    }
}
