# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  api:
    image: ${DOCKER_IMAGE:-odh-tourism-api}:${DOCKER_TAG:-latest}
    build:
      context: ../
      dockerfile: OdhApiCore/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ConnectionStrings__PgConnection: ${PG_CONNECTION}
      ASPNETCORE_MssConfig__Username: ${MSS_USER}
      ASPNETCORE_MssConfig__Password: ${MSS_PSWD}
      ASPNETCORE_MssConfig__ServiceUrl: ${MSS_SERVICEURL}
      ASPNETCORE_LcsConfig__Username: ${LCS_USER}
      ASPNETCORE_LcsConfig__Password: ${LCS_PSWD}
      ASPNETCORE_LcsConfig__MessagePassword: ${LCS_MSGPSWD}
      ASPNETCORE_LcsConfig__ServiceUrl: ${LCS_SERVICEURL}
      ASPNETCORE_SiagConfig__Username: ${SIAG_USER}
      ASPNETCORE_SiagConfig__Password: ${SIAG_PSWD}
      ASPNETCORE_SiagConfig__ServiceUrl: ${SIAG_SERVICEURL}
      ASPNETCORE_XmlConfig__XmldirWeather: ${XMLDIR}
      ASPNETCORE_Xmldir__Xmldir: ${XMLDIR}
      ASPNETCORE_S3ImageresizerConfig__Url: ${IMG_URL}
      ASPNETCORE_S3ImageresizerConfig__BucketAccessPoint: ${S3_BUCKET_ACCESSPOINT}
      ASPNETCORE_S3ImageresizerConfig__AccessKey: ${S3_IMAGEUPLOADER_ACCESSKEY}
      ASPNETCORE_S3ImageresizerConfig__SecretKey: ${S3_IMAGEUPLOADER_SECRETKEY}
      ASPNETCORE_OauthServerConfig__Authority: ${OAUTH_AUTORITY}
      ASPNETCORE_ProxyConfig__CaddyTest: ${CADDY_TEST_IP}
      ASPNETCORE_ProxyConfig__CaddyProd: ${CADDY_PROD_IP}
      ASPNETCORE_ElasticSearchConfig__ElasticUrl: ${ELK_URL}
      ASPNETCORE_ElasticSearchConfig__ElasticAuthtoken: ${ELK_TOKEN}
      ASPNETCORE_JsonConfig__Jsondir: ${JSONPATH}
      ASPNETCORE_DataBrowserConfig__Url: ${DATABROWSER_URL}
      ASPNETCORE_FCMConfig__noi-communityapp__ServerKey: ${NOICOMMUNITY_SERVERKEY}
      ASPNETCORE_FCMConfig__noi-communityapp__SenderId: ${NOICOMMUNITY_SENDERID}
      ASPNETCORE_FCMConfig__noi-communityapp__ProjectName: ${NOICOMMUNITY_PROJECTNAME}
      ASPNETCORE_FCMConfig__noi-communityapp__FCMServiceAccount: ${NOICOMMUNITY_FCMSERVICEACCOUNT}      
      ASPNETCORE_NotifierConfig__idm-marketplace__Url: ${MARKETPLACE_PUSH_URL}
      ASPNETCORE_NotifierConfig__idm-marketplace__User: ${MARKETPLACE_PUSH_USER}
      ASPNETCORE_NotifierConfig__idm-marketplace__Password: ${MARKETPLACE_PUSH_PSWD}
      ASPNETCORE_NotifierConfig__idm-marketplace__Header: ${MARKETPLACE_PUSH_HEADER}
      ASPNETCORE_NotifierConfig__idm-marketplace__Token: ${MARKETPLACE_PUSH_TOKEN}
      ASPNETCORE_S3Config__dc-meteorology-province-forecast__Filename: ${S3_WEATHERFORECAST_FILENAME}
      ASPNETCORE_S3Config__dc-meteorology-province-forecast__AccessKey: ${S3_WEATHERFORECAST_ACCESSKEY}
      ASPNETCORE_S3Config__dc-meteorology-province-forecast__AccessSecretKey: ${S3_WEATHERFORECAST_SECRET}
      ASPNETCORE_LTSApiIDM__ServiceUrl: ${LTSAPI_IDM_SERVICEURL}
      ASPNETCORE_LTSApiIDM__Username: ${LTSAPI_IDM_USERNAME}      
      ASPNETCORE_LTSApiIDM__Password: ${LTSAPI_IDM_PASSWORD}
      ASPNETCORE_LTSApiIDM__XLSClientid: ${LTSAPI_IDM_XLTSCLIENTID}
      ASPNETCORE_LTSApiIDM__Opendata: ${LTSAPI_IDM_OPENDATA}
      ASPNETCORE_LTSApiOpen__ServiceUrl: ${LTSAPI_OPENDATA_SERVICEURL}
      ASPNETCORE_LTSApiOpen__Username: ${LTSAPI_OPENDATA_USERNAME}      
      ASPNETCORE_LTSApiOpen__Password: ${LTSAPI_OPENDATA_PASSWORD}
      ASPNETCORE_LTSApiOpen__XLSClientid: ${LTSAPI_OPENDATA_XLTSCLIENTID}
      ASPNETCORE_LTSApiOpen__Opendata: ${LTSAPI_OPENDATA_OPENDATA}
      ASPNETCORE_DigiWayConfig__cyclewaystyrol__ServiceUrl: ${DIGIWAY_CYCLEWAYSTIROL_URL}
      ASPNETCORE_DigiWayConfig__mountainbikeroutes__ServiceUrl: ${DIGIWAY_MTBROUTES_URL}
      ASPNETCORE_DigiWayConfig__hikingtrails__ServiceUrl: ${DIGIWAY_HIKINGTRAILS_URL}
      ASPNETCORE_DigiWayConfig__intermunicipalcyclingroutes__ServiceUrl: ${DIGIWAY_INTERMUNICIPALCYCLINGROUTES_URL}
      ASPNETCORE_GTFSApiConfig__StaTimetables__ServiceUrl: ${GTFSAPI_STATIMETABLES_URL}
    ports:
      - "8001:80"
